#!/bin/bash
# Fetch root CA certs for SmartSwitch TLS validation.
# Run this to renew certs.h when root CAs change.
# Usage: ./fetch_certs.sh  (from workspace root)
#
# Only the OTA path uses TLS: api.github.com serves the release metadata,
# objects.githubusercontent.com the firmware asset after the redirect.
# Servers usually send their chain up to an intermediate, not up to the root -
# pinning that intermediate breaks as soon as the CA rotates it. So the issuer of
# the last chain element is looked up in the local trust store and that root is pinned.

set -e

OUT="smartswitch.espxx/include/certs.h"
TRUST_STORE=/etc/ssl/certs/ca-certificates.crt

HOSTS=(api.github.com objects.githubusercontent.com)

get_last_chain_cert() {
  local host=$1
  openssl s_client -connect "$host:443" -servername "$host" -showcerts </dev/null 2>/dev/null |
    awk '/-----BEGIN CERTIFICATE-----/{cert=""} {cert=cert $0 "\n"} /-----END CERTIFICATE-----/{last=cert} END{printf "%s", last}'
}

cert_field() { # $1 = pem, $2 = -subject|-issuer
  echo "$1" | openssl x509 -noout "$2" 2>/dev/null | sed -e 's/.*CN\s*=\s*//' -e 's/,.*//'
}

find_in_trust_store() { # $1 = subject CN
  local want=$1 cert=""
  while IFS= read -r line; do
    cert+="$line"$'\n'
    if [ "$line" = "-----END CERTIFICATE-----" ]; then
      if [ "$(cert_field "$cert" -subject)" = "$want" ]; then
        printf '%s' "$cert"
        return 0
      fi
      cert=""
    fi
  done <"$TRUST_STORE"
  return 1
}

root_ca_for() { # $1 = host - prints the root pem, falls back to the last chain element
  local host=$1 chain root
  chain=$(get_last_chain_cert "$host")
  if root=$(find_in_trust_store "$(cert_field "$chain" -issuer)"); then
    printf '%s' "$root"
  else
    printf '%s' "$chain"
  fi
}

SUMMARY=()

{
  cat <<'HEADER'
#pragma once
// Auto-generated by fetch_certs.sh — do not edit manually.
// Re-run fetch_certs.sh to renew when root CAs expire.
#ifdef ESP32
static const char ROOT_CA_BUNDLE[] PROGMEM =
HEADER

  for host in "${HOSTS[@]}"; do
    echo "Fetching root CA for ${host} ..." >&2
    ca=$(root_ca_for "$host")
    cn=$(cert_field "$ca" -subject)
    exp=$(echo "$ca" | openssl x509 -noout -enddate 2>/dev/null | sed 's/notAfter=//')

    printf '  // %s — %s, expires %s\n' "$host" "$cn" "$exp"
    echo "$ca" | sed 's/\(.*\)/  "\1\\n"/'

    SUMMARY+=("  ${host}: CN=${cn}, expires ${exp}")
  done

  cat <<'FOOTER'
  ;
#endif // ESP32
FOOTER
} >"$OUT"

echo ""
echo "${OUT} updated."
printf '%s\n' "${SUMMARY[@]}"
