#
# docker run --rm -p 8080:80 --name nginx -v $(pwd):/usr/share/nginx/html:ro -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf:ro nginx

server {
    listen 80;
    server_name localhost;
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  0;

    charset utf-8;

    # stealth mode
    server_tokens off;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api {
        #proxy_pass http://192.168.188.45;
        proxy_pass http://192.168.188.47;
    }

    location /update {
        proxy_pass http://192.168.188.45;
    }
}