#
# docker run --rm -p 8080:8080 -p 8081:8081 --name nginx -v $(pwd):/usr/share/nginx/html:ro -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf:ro nginx

worker_processes auto;

events {
    worker_connections 1024;
}

http {

  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;

  server {
      listen 8080;
      server_name   localhost;
      include       mime.types;
      default_type  application/octet-stream;

      sendfile        on;
      keepalive_timeout  0;

      charset utf-8;

      # stealth mode
      server_tokens off;

      location / {
          root /usr/share/nginx/html;
          index index.html;
      }

      location /api {
          proxy_pass http://192.168.188.44;
      }

      location /update {
          proxy_pass http://192.168.188.44;
      }
  }
  server {
      listen 8081;
      server_name   localhost;
      include       mime.types;
      default_type  application/octet-stream;

      sendfile        on;
      keepalive_timeout  0;

      charset utf-8;

      # stealth mode
      server_tokens off;

      location / {
          root /usr/share/nginx/html;
          index index.html;
      }

      location /api {
          proxy_pass http://192.168.188.21;
      }

      location /update {
          proxy_pass http://192.168.188.21;
      }
  }

  server {
    listen 8080;
    server_name
      192.168.188.20
    ;

    location / {
      proxy_pass https://api.forecast.solar;

      proxy_cache my_cache;
      proxy_cache_valid 200 302 30m;
      proxy_cache_valid 404 1m;
      proxy_cache_use_stale error timeout updating;
      proxy_cache_background_update off;
      proxy_cache_lock on;

      # Headers
      #proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_ignore_headers Cache-Control Expires;
      add_header X-Cache-Status $upstream_cache_status always;
    }
  }
}