---
name: Build Sonnen SmartSwitch Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install WiFiManager@2.0.17 ArduinoJson@7.4.2 ESPAsyncWebServer@3.1.0 AsyncTCP@1.1.4 ESPAsyncTCP@1.2.4
          # ElegantOTA@3.1.5

      - name: Compile Sketch
        run: arduino-cli compile -e --fqbn esp8266:esp8266:d1_mini_clone:xtal=80,vt=flash,exception=disabled,stacksmash=disabled,ssl=all,mmu=4816,non32xfer=fast,FlashMode=dout,FlashFreq=40,eesz=4M1M --warnings all ./src/smartswitch.esp8266

      - name: Compress artifact
        run: gzip -9 -k src/smartswitch.esp8266/build/esp8266.esp8266.d1_mini_clone/smartswitch.esp8266.ino.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: smartswitch-binary
          path: src/smartswitch.esp8266/build/esp8266.esp8266.d1_mini_clone/smartswitch.esp8266.ino.bin.gz
          retention-days: 1 # delete after build

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: smartswitch-binary
          path: .

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: Automatically generated release ${{ github.run_number }}
          draft: false
          prerelease: false
          artifactContentType: "application/gzip"
          artifacts: |
            smartswitch.esp8266.ino.bin.gz
